- Smile/src/main/java/smile/util/MulticoreExecutor.java
- Smile/src/main/java/smile/util/SimpleDeamonThreadFactory.java
The threads created by the MulticoreExecutor prevented the JVM from exiting after the computation is finished. I use smile from scala using sbt, and this prevented the computation from exiting cleanly while leaving sbt running. I had to kill the JVM to terminate the program (including sbt which runs in the same JVM as the code). Setting the threads as daemons solved the problem.
> set threads as daemons

- .gitignore
- Smile/pom.xml
- SmileData/pom.xml
- SmileDemo/pom.xml
- SmileGraph/pom.xml
- SmileInterpolation/pom.xml
- SmileMath/pom.xml
- SmileNLP/pom.xml
- SmilePlot/pom.xml
- pom.xml
The reason was -Xdoclint:none specified in javadoc plugin was not recognized.
The problem should be solved by adding a profile which only adds the switch if JDK >= 1.8 is detected.
Also added /target directories to .gitignore.
> Build was failing with maven 3.3.3 on JDK7

- math/src/main/java/smile/math/Math.java
Access to the utility Random was synchronized on a method level instead
of an object level.
Not sure if this is how you want to fix it, but I was running into this Exception when I had multiple threads learning/clustering/etc. across multiple core objects that use the Math util internally.  I just went with the easiest fix.
> Fix ArrayIndexOutOfBoundsException when accessing math util's random.

- nlp/src/main/java/smile/nlp/tokenizer/PennTreebankTokenizer.java
- nlp/src/main/java/smile/nlp/tokenizer/SimpleTokenizer.java
- nlp/src/test/java/smile/nlp/tokenizer/PennTreebankTokenizerTest.java
- nlp/src/test/java/smile/nlp/tokenizer/SimpleTokenizerTest.java
Hi Haifeng,
The SimpleTokenizer and PennTreebankTokenizer rely on the regex character class `\w` in the first delimiter pattern. Unfortunately, `\w` only matches the ASCII letters and numbers, so words with diacritized characters or non-Latin characters are not recognized as tokens. For example, `résumé` is tokenized as `["r", "é", "sum", "é"]`. 
I replaced `\w` with the following: `\p{L}\p{N}\p{M}\p{Sk}\u200C\u200D`. This expression matches the unicode letter category (L), the number category (N), the marks category (M, which includes combining diacritics), some miscellaneous diacritics (Sk), and the zero-width non-joiner and joiner characters (used word-internally mostly in Arabic script but sometimes in other languages).
These changes should improve tokenization on English and European …
> Make Simple and PennTreebank tokenizers Unicode-aware

- nlp/src/main/java/smile/nlp/normalizer/Normalizer.java
- nlp/src/main/java/smile/nlp/normalizer/SimpleNormalizer.java
- nlp/src/test/java/smile/nlp/normalizer/SimpleNormalizerTest.java
- nlp/src/test/java/smile/nlp/tokenizer/SimpleSentenceSplitterTest.java
Haifeng,
While using Smile's tokenizer and pos-tagger, I came across a need to perform basic text normalization. I added a normalization interface and a simple normalizer that applies the Unicode normalization form NFKC, trims/compresses/normalizes whitespace, removes formatting and control characters, and replaces non-ASCII double and single quotes (i.e. "curly quotes") with their ASCII versions. I hope others might find it useful.
> Text normalization

- plot/src/main/java/smile/swing/table/DoubleArrayCellRenderer.java
- plot/src/main/java/smile/swing/table/FloatArrayCellRenderer.java
- plot/src/main/java/smile/swing/table/FontCellRenderer.java
- plot/src/main/java/smile/swing/table/IntegerArrayCellRenderer.java
- plot/src/main/java/smile/swing/table/LongArrayCellRenderer.java
- plot/src/main/java/smile/swing/table/ShortArrayCellRenderer.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S2259 - Null pointers should not be dereferenced
You can find more information about the issue here:  
https://dev.eclipse.org/sonar/rules/show/squid:S2259
Please let me know if you have any questions.
Ayman Elkfrawy.
> Fix: squid:S2259, Null pointers should not be dereferenced

- core/src/main/java/smile/classification/SVM.java
- core/src/main/java/smile/clustering/MEC.java
- core/src/main/java/smile/neighbor/CoverTree.java
- core/src/main/java/smile/taxonomy/Concept.java
- core/src/main/java/smile/vq/GrowingNeuralGas.java
- core/src/main/java/smile/vq/NeuralMap.java
- core/src/test/java/smile/neighbor/LSHTest.java
- core/src/test/java/smile/neighbor/MPLSHTest.java
- core/src/test/java/smile/neighbor/SNLSHTest.java
- graph/src/main/java/smile/graph/AdjacencyList.java
- graph/src/main/java/smile/graph/AdjacencyMatrix.java
- math/src/main/java/smile/stat/distribution/DiscreteMixture.java
- nlp/src/main/java/smile/nlp/pos/HMMPOSTagger.java
- nlp/src/main/java/smile/nlp/tokenizer/BreakIteratorTokenizer.java
- nlp/src/test/java/smile/nlp/pos/HMMPOSTaggerTest.java
- plot/src/main/java/smile/plot/Axis.java
- plot/src/main/java/smile/plot/Contour.java
- plot/src/main/java/smile/swing/FontChooser.java
- plot/src/main/java/smile/swing/table/DefaultTableHeaderCellRenderer.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1155 - “Collection.isEmpty() should be used to test for emptiness”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1155
Please let me know if you have any questions.
Ayman Elkfrawy.
> Fix: squid:S1155, Using Collection.isEmpty() to test for emptiness

- core/src/main/java/smile/classification/AdaBoost.java
- data/src/main/java/smile/data/Dataset.java
- data/src/main/java/smile/data/parser/ArffParser.java
- demo/src/main/java/smile/demo/clustering/CLARANSDemo.java
- demo/src/main/java/smile/demo/clustering/ClusteringDemo.java
- demo/src/main/java/smile/demo/plot/BarPlotDemo.java
- demo/src/main/java/smile/demo/vq/BIRCHDemo.java
- plot/src/main/java/smile/plot/Base.java
- plot/src/main/java/smile/plot/Contour.java
This pull request is focused on resolving occurrences of Sonar rule 
squid:S1192 - “String literals should not be duplicated”. 
You can find more information about the issue here: 
https://dev.eclipse.org/sonar/rules/show/squid:S1192
Please let me know if you have any questions.
Ayman Elkfrawy.
> Fix: squid:S1192, String literals should not be duplicated

- core/src/main/java/smile/classification/RandomForest.java
- data/src/main/java/smile/data/Attribute.java
Right now the inner class `RandomForest$Tree` is not serializable, so I get the following when I try to save the model:
```
Caused by: java.io.NotSerializableException: smile.classification.RandomForest$Tree
at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1184)
at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:348)
```
This simple modification should make it work
> making RandomForest serializable

- data/src/main/java/smile/data/SparseDataset.java
Sometimes I want to specify both the number of columns and the type of the response variable when creating a sparse dataset. This small patch solves this problem.
> ncol+attribute constructor for SparseDataset

- project/build.properties
Specify SBT version as a project property. 
That way, local updates won't break the compilation.
> Explicit SBT version

- math/src/main/java/smile/stat/distribution/BernoulliDistribution.java
fixed a bug which caused an ArrayOutOfBoundException in case of negative integers in data[]
> Negative Values in Bernoulli Constructor should throw correct error 

- core/src/main/java/smile/validation/CrossValidation.java
Add additional constructor to CrossValidation so users can choose if they don't want the indices to be permutated.
> Add additional constructor to CrossValidation

- data/src/main/java/smile/data/parser/DelimitedTextParser.java
- data/src/test/java/smile/data/parser/DelimitedTextParserTest.java
Adds the possibility to ignore some columns with DelimitedTextParser. By default, all columns are read. You can add column indices to ignore with the methods `setIgnoredColumns`, `addIgnoredColumn` and `addIgnoredColumns`. If `hasRowNames` is true, the first column is ignored. The response variable cannot be ignored.
> Ignoring some columns with DelimitedTextParser

- core/src/main/java/smile/regression/RandomForest.java
- core/src/test/java/smile/regression/RandomForestTest.java
Add an option to merge two random forests into one
Example use cases:
* Build random forests on spark executors and then merge them together into one big forest on driver.
* Grow forest iteratively over time
> Add regression random forest merging capability

- project/build.properties
- project/plugins.sbt
It's a security issue to use http for a resolver. The jars you download could be switched out for malicious versions. See here: https://max.computer/blog/how-to-take-over-the-computer-of-any-java-or-clojure-or-scala-developer/
> Upgrade SBT and use https for resolvers

- core/src/main/java/smile/regression/OLS.java
- data/src/main/java/smile/data/AttributeDataset.java
Partially addresses https://github.com/haifengl/smile/issues/297. There are probably other algorithms where this would be useful as well
I implemented this with a simple `String[]`. However, it may be preferable to use a dataframe like [Tablesaw](https://github.com/jtablesaw/tablesaw) similar to Spark's dataframe. If you would like, I could send a PR to utilize a dataframe as a nicer datastructure for this information.
> Include variable names for OLS

- core/src/main/java/smile/classification/AdaBoost.java
- core/src/main/java/smile/classification/GradientTreeBoost.java
- core/src/main/java/smile/classification/RandomForest.java
- core/src/main/java/smile/regression/GradientTreeBoost.java
- core/src/main/java/smile/regression/RandomForest.java
- core/src/main/java/smile/regression/RegressionTree.java
AttributeDataset is often much easier to construct because you can convert arff files, Tablesaw tables, etc. to `AttributeDataset`
We probably don't need constructors taking `Attribute[] attributes, double[][] x, int/double[] y` as it's easier to just pass an `AttributeDataset` but I left them for backwards compatibility
> Add constructors taking AttributeDataset

- core/src/main/java/smile/clustering/FastPair.java
It appears that the distance array was incorrectly set the point index instead of the calculate linkage distance. Based on other usage of linkage distance in this class this appears to be the correct behavior.
> Minor Typo in FastPair Method updateDistance

- math/src/main/java/smile/math/Math.java
there was a bug in c(int[]... x) at line 930 (and other similar).  x.length was the # arguments to the function, not the length of one of the vectors.  Fixed.  Also, the c(String[]... x) can take a generic type and use .toString() to collect the results.  If already a String, it's a no-op.
Also, I think cat (as in catenate) would be a better name than just c, if you're willing to change it.
> bugfix in Math.java

- core/src/main/java/smile/clustering/PartitionClustering.java
Hi
I'm trying to serialize a DBSCAN instance, store it on disk, and deserialize when needed in order to use the `predict` method. the goal is to evaluate new datapoints without recomputing everything.
The issue is that even if `DBSCAN<T>` is declared Serializable, its parent class PartitionClustering is not. So java serialization process will NOT serialize fields inherited from the parent class (`k`, `y`, `size`). That makes the deserialized class unusable since these values are lost.
This PR just add Serializable to the PartitionClustering class.
> PartitionClustering should be Serializable

- core/src/main/java/smile/classification/DecisionTree.java
I found that smile's decision tree produces a lot of redundant branches as seen in 
https://user-images.githubusercontent.com/1163783/27733149-8a1927d8-5dcf-11e7-873b-9f0d37e19733.png
So, this PR prune redundant branches as follows:
Before: 
```javascript
if( sibsp <= 2.5 ) {
if( age <= 15.5 ) {
if( age <= 0.5 ) {
if( sibsp <= 1.5 ) {
if( parch <= 1.5 ) {
no;
} else  {
no;
}
} else  {
yes;
}
} else  {
if( age <= 11.5 ) {
if( fare <= 14.33125 ) {
yes;
} else  {
yes;
}
} else  {
yes;
}
}
} else  {
no;
}
} else  {
no;
}
```
After:
```javascript
if( sibsp <= 2.5 ) {
if( age <= 15.5 ) {
if( age <= 0.5 ) {
if( sibsp <= 1.5 ) {
no;
} else  {
yes;
}
} else  {
yes;
}
} else  {
no;
}
} else  {
no;
}
```
This is a back-port of [my modification](https://github.com/apache/incubator-hivemall/pull/198) …
> Prune redundant branches in DecisionTrees

- core/src/main/java/smile/classification/LogisticRegression.java
- core/src/main/java/smile/classification/Maxent.java
- core/src/test/java/smile/classification/MaxentTest.java
This addresses additional places where the same pattern in #458 is used. Also fixes a golden number in MaxentTest, which was causing test failures at HEAD.
> Fix more places where tasks might use invalid bounds.

- core/src/main/java/smile/neighbor/KDTree.java
`lowerBound` and `upperBound` were being allocated once per tree level per data object, then left for the garbage collector to clean up. This is wasteful.
> Speed up tree creation by eliminating temporary allocations

- core/src/main/java/smile/feature/EnsembleTreeSHAP.java
- core/src/test/java/smile/data/BostonHousing.java
- core/src/test/java/smile/feature/TreeShapTest.java
implementation for https://github.com/haifengl/smile/issues/515
similar (although not exactly same) [python ](https://github.com/slundberg/shap#tree-ensemble-example-with-treeexplainer-xgboostlightgbmcatboostscikit-learnpyspark-models) result for boston housing dataset:
```
CRIM      4.7090670e-01
ZN        1.1862384e-03
INDUS     3.6680367e-02
CHAS      0.0000000e+00
NOX       2.9865596e-01
RM        1.6684741e+00
AGE       3.4423586e-02
DIS       2.4549793e-01
RAD       1.1467161e-02
TAX       4.9007054e-02
PTRATIO   9.5596902e-02
B         8.1507929e-02
LSTAT     2.5720918e+00
```
> ensemble tree shap

- plot/src/main/java/smile/plot/swing/BarPlot.java
`smile.plot.swing.BarPlot` allows setting legends but currently they are not displayed.
There is also a small typo in an array index which leads to odd plots if `smile.plot.swing.BarPlot#of(double[][], java.lang.String[])` is used.
> Polish BarPlot legends and data

- scala/src/main/scala/smile/math/package.scala
This is a single line change (5 character insertion) to fix a very obvious bug in "ones" when the matrix is not square. It currently returns a matrix of zeros rather than a matrix of ones in that case.
> Fixed bug in "ones"

- scala/src/main/scala/smile/data/DataFrame.scala
`l :+ i` returns a copy of the original collection with `i` appended, hence `l` and `r` are always empty
`l += i` appends `i` to the original collection, hence `l` and `r` will contain the required partitioning
> Fix scala DataFrameOps partition

- shell/src/universal/bin/jupyterlab.sh
- web/quickstart.html
Issue #671
- setting scala version back to 2.13.4
- setting `main-class`
- Updating github.io website to note location of script `took second to find` 
Kernel is installed and working
> Coursier Bootstrapping #671

- math/src/main/java/smile/math/DifferentiableMultivariateFunction.java
Commit 0a1bff0f6f301fc81ab123737d02823ab8e44da5 introduced a bug in the `AbstractDifferentiableMultivariateFunction` (now `DifferentiableMultivariateFunction`) gradient computation by incorrectly initializing `xh`.
This can be easilly tested in the scala console with:
```scala
val f: smile.math.DifferentiableMultivariateFunction = (x: Array[Double]) => x(0)*x(0) + x(1)*x(1) + x(2)*x(2)
val grad = Array(0.0, 0.0, 0.0)
f.g(Array(5,5,5), grad)
println(grad)
```
The version in `master` incorrectly computes the gradient as `Array(-9.99999996077471E8, -4.9999999303873545E8, 10.000000035527137)`, while now it's correctly computed as `Array(10.000000035527137, 10.000000035527137, 10.000000035527137)`
> Fix xh initialization in gradient computation

- nlp/src/main/java/smile/nlp/relevance/BM25.java
- nlp/src/test/java/smile/nlp/relevance/BM25Test.java
This PR implements the suggestions of #682 by adjusting the IDF formula within the _BM25.java_ class at three places. Due to this change, the expected value of the corresponding unit test changed slightly and is hence adjusted as well.
Please tell me if something is wrong with this PR or if you do not see a need for this formula change. Thanks in advance!
> Avoid negative BM25 scores

- base/src/main/java/smile/util/Paths.java
It might help to add `/data` sub-folder in default system property value directly instead using string concatenation later. And plain string concatenation would encounter path seperator issue across platforms like Linux(using `/`) and Windows (using `\\` in Java).
For example, in Windows, with proposed change, developer could run the unit test with java option `-Dsmile.home=C:\smile\shell\src\universal\data` to override the default value
> fix test data path
