haifengl/smile

Smile/test/smile/feature/BagTest.java
Added a unit test that covers issue #6 which was fixed with commit  https://github.com/haifengl/smile/commit/1a0afa464ebd3c2cc11e7a61d3279d60c9edc602
=> Unit test for the bag IndexOutOfBoundsException

SmilePlot/src/smile/plot/ScatterPlot.java
=> Made Scatterplot label values more flexible

README.md
Changed "avilable" to "available".
=> Fixed tiny typo.

Smile/src/main/java/smile/neighbor/LSH.java
Hi Haifeng,
Thank you for all your efforts. This commit change the way removing duplicated candidates, avoiding ordering, the running time of the toy data can be reduced almost half.
By the way, I have been working on LSH based on SimHash or MinHash for weeks, and I'm wondering if I could contribute to this amazing project :~)
Qiyang
=> Use set to remove the duplicate candidates

Smile/src/main/java/smile/validation/ConfusionMatrix.java, Smile/src/test/java/smile/validation/ConfusionMatrixTest.java
finally, pull request from issue #32
=> Confusion Matrix implementation to compute multi-class precision, recall and f-measure

Smile/src/main/java/smile/classification/DecisionTree.java, SmileMath/src/main/java/smile/math/kernel/HellingerKernel.java, SmileMath/src/main/java/smile/math/kernel/PearsonKernel.java
New kernels and split rule added.
=> Kernels and new split rule added.

core/src/main/java/smile/vq/SOM.java
Haifeng,
I am currently working with SOMs and your library.  While I can create a umatrix and plot it, I wanted to add a method to SOM to allow for the retrieval of class values for each of the Neurons.  Ideally, this would be run after calling partition(int).  This could be used to create more effective class graphs of the SOM.
=> SOM Neuron Class Retrieval

scala/src/main/scala/smile/data/package.scala
Hi @haifengl, I've simplified a little bit the scala data package. What do you think?
=> Simplify scala data package

scala/src/main/scala/smile/classification/Operators.scala, scala/src/main/scala/smile/data/package.scala, scala/src/main/scala/smile/regression/Operators.scala
Removed some duplication. What do you think @haifengl ?
=> Factor out default attributes for classification and regression.

core/src/main/java/smile/classification/SVM.java, core/src/test/java/smile/classification/SVMTest.java
Can´t run the test locally, mabye you can give it a try :)
=> Allow to query if Platt scaling has been executed.

symbolic/src/main/java/smile/symbolic/Calculus.java, symbolic/src/main/java/smile/symbolic/Evaluation.java, symbolic/src/main/java/smile/symbolic/ExpressionParser.java, symbolic/src/main/java/smile/symbolic/ExpressionTree.java, symbolic/src/main/java/smile/symbolic/InvalidExpressionException.java, symbolic/src/main/java/smile/symbolic/internal/BinaryNode.java, symbolic/src/main/java/smile/symbolic/internal/Constant.java, symbolic/src/main/java/smile/symbolic/internal/Cosecant.java, symbolic/src/main/java/smile/symbolic/internal/Cosine.java, symbolic/src/main/java/smile/symbolic/internal/Cotangent.java, symbolic/src/main/java/smile/symbolic/internal/Difference.java, symbolic/src/main/java/smile/symbolic/internal/Exponent.java, symbolic/src/main/java/smile/symbolic/internal/Expression.java, symbolic/src/main/java/smile/symbolic/internal/Logarithm.java, symbolic/src/main/java/smile/symbolic/internal/NaturalLogarithm.java, symbolic/src/main/java/smile/symbolic/internal/Negation.java, symbolic/src/main/java/smile/symbolic/internal/Product.java, symbolic/src/main/java/smile/symbolic/internal/Quotient.java, symbolic/src/main/java/smile/symbolic/internal/ReductionRules.java, symbolic/src/main/java/smile/symbolic/internal/Secant.java, symbolic/src/main/java/smile/symbolic/internal/Sine.java, symbolic/src/main/java/smile/symbolic/internal/Sum.java, symbolic/src/main/java/smile/symbolic/internal/Tangent.java, symbolic/src/main/java/smile/symbolic/internal/UnaryNode.java, symbolic/src/main/java/smile/symbolic/internal/Variable.java, symbolic/src/test/java/smile/symbolic/BaseTest.java, symbolic/src/test/java/smile/symbolic/mathematicsTest/CalcTest.java, symbolic/src/test/java/smile/symbolic/mathematicsTest/CalculusTest.java, symbolic/src/test/java/smile/symbolic/mathematicsTest/ExpressionParserTest.java, symbolic/src/test/java/smile/symbolic/mathematicsTest/ExpressionTreeTest.java
I must admit that I created this system more from intuition than from research.  There is a lot of work to be done to make it perfect, but I think it is off to an excellent start.
=> Add symbolic classes and tests

shell/src/universal/doc/classification-content.html, shell/src/universal/doc/faq-content.html, shell/src/universal/doc/feature-content.html, shell/src/universal/doc/validation-content.html, shell/src/universal/doc/visualization-content.html
=> fix:read.table parms error

math/src/main/java/smile/math/random/MersenneTwister.java
Calling setSeed on MersenneTwister used to result in StackOverflow with infinite recursion
=> Fix infinite recursion when calling setSeed with long

core/src/main/java/smile/classification/NaiveBayes.java, demo/src/main/java/smile/demo/classification/ClassificationDemo.java, demo/src/main/java/smile/demo/classification/NaiveBayesDemo.java
This PR 
- adds demo for NaiveBayes classification using Iris data set (use only 2 out of total 4 features for demo purpose)
- adds PolyaUrn model in NaiveBayes : https://en.wikipedia.org/wiki/P%C3%B3lya_urn_model
=> add demo for Naive Bayes with Iris and add PolyaUrn model

core/src/main/java/smile/association/FPGrowth.java, core/src/test/java/smile/association/FPGrowthTest.java
Hi,
This PR fixes the issue in FPGrowth when mining a single path tree.
Cheers,
Peter
=> Fixes FP-Growth single path FP-tree mining

core/src/main/java/smile/sequence/CRF.java
=> Make CRF model serializable

core/src/main/java/smile/classification/LogisticRegression.java, core/src/test/java/smile/classification/LogisticRegressionTest.java, math/src/main/java/smile/math/Math.java
add stochastic gradient descent for Logistic Regression
reference: http://www.cs.cmu.edu/~wcohen/10-605/sgd-part2.pdf
=> add sgd for Logistic Regression

core/src/main/java/smile/validation/MCCMeasure.java, core/src/test/java/smile/validation/MCCTest.java, scala/src/main/scala/smile/validation/Operators.scala
add MCC metric for binary classification
=> Add MCC metric

plot/src/main/java/smile/plot/Heatmap.java
By the way, thanks for all the great work on this project!
=> Fix bug in Heatmap.java: x and y arrays are not passed to constructor

core/src/main/java/smile/classification/RandomForest.java
mtry needs to be set when Trainer is created.
=> mtry needs to be set for Trainer

core/src/main/java/smile/validation/GroupKFold.java, core/src/test/java/smile/validation/GroupKFoldTest.java
Implements the proposed feature in https://github.com/haifengl/smile/issues/377.
=> Implement the GroupKFold functionality

graph/src/main/java/smile/graph/package-info.java, math/src/main/java/smile/math/matrix/MatrixElementConsumer.java, math/src/main/java/smile/math/matrix/SparseMatrix.java, math/src/test/java/smile/math/matrix/SparseMatrixTest.java
This relates to issue #446 (Need some iterators on SparseMatrix)
=> Add functional iterators to SparseMatrix

core/src/main/java/smile/classification/DecisionTree.java, core/src/main/java/smile/classification/RandomForest.java
This should help somewhat with https://github.com/haifengl/smile/issues/257 and https://github.com/haifengl/smile/issues/70
=> Speed up DecisionTree training by partitioning the order arrays

core/src/main/java/smile/classification/DecisionTree.java
This fixes some issues in https://github.com/haifengl/smile/pull/448 that myui pointed out; I also noticed that I hadn't updated a comment after a prior code revision.
=> Fix minor issues from previous pull request; update a comment.

core/src/test/java/smile/data/Puma8NH.java
=> Fix case in test input filename

spark/src/main/scala/smile/spark/package.scala, spark/src/test/scala/smile/spark/GridSpec.scala
=> Fix spark tuning test

web/index.html
🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.
Please describe your pull request.
❤️ Thank you!
=> Add Groovy example #631
